# Generated by Django 5.2 on 2025-04-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
