# Generated by Django 5.2 on 2025-04-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_eventdetail_delete_event'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventdetail',
            table='event_details',
        ),
    ]
