# Generated by Django 5.2 on 2025-04-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_eventdetail_district_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdetail',
            options={'managed': False},
        ),
    ]
