# Generated by Django 5.2 on 2025-04-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_eventdetail_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('japanese', models.CharField(max_length=255)),
                ('english', models.CharField(max_length=255)),
                ('korean', models.CharField(max_length=255)),
                ('station_code', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
