# Generated by Django 5.2 on 2025-04-29 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_facilityinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('place_id', models.CharField(blank=True, max_length=255)),
                ('photo_reference', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='myapp.stationinfo')),
            ],
        ),
    ]
