# Generated by Django 5.2 on 2025-04-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_nearbyfacility'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationinfo',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationinfo',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
