# Generated by Django 5.2 on 2025-04-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_stationinfo_lat_stationinfo_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationinfo',
            name='photo_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
