# Generated by Django 5.2 on 2025-04-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_stationinfo_photo_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityinfo',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
