# Generated by Django 5.2 on 2025-04-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_facilityinfo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearbyfacility',
            name='address',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
