# Generated by Django 5.2 on 2025-04-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_nearbyfacility_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearbyfacility',
            name='photo_reference',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
