# Generated by Django 5.2 on 2025-04-30 11:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_nearbyfacility_photo_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationinfo',
            name='mood',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
    ]
