# Generated by Django 5.2 on 2025-04-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_stationinfo_mood'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=50)),
                ('room_type', models.CharField(max_length=20)),
                ('station', models.CharField(max_length=50)),
                ('rent_price', models.FloatField()),
            ],
        ),
    ]
