# Generated by Django 5.2 on 2025-04-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rentinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentinfo',
            name='rent_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
