# Generated by Django 5.2 on 2025-04-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_rentinfo_rent_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbyfacility',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='facility_photos/'),
        ),
    ]
