# Generated by Django 5.2 on 2025-05-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_nearbyfacility_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=100, verbose_name='Station Name')),
                ('hub', models.CharField(max_length=100, verbose_name='Destination Hub')),
                ('distance_m', models.IntegerField(verbose_name='Straight-line Distance (m)')),
                ('duration_min', models.IntegerField(blank=True, null=True, verbose_name='Bicycle Duration (min)')),
            ],
            options={
                'verbose_name': 'Bicycle Travel Time',
                'verbose_name_plural': 'Bicycle Travel Times',
                'unique_together': {('station', 'hub')},
            },
        ),
        migrations.CreateModel(
            name='TransitDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=100, verbose_name='Station Name')),
                ('hub', models.CharField(max_length=100, verbose_name='Destination Hub')),
                ('distance_m', models.IntegerField(verbose_name='Straight-line Distance (m)')),
                ('duration_min', models.IntegerField(blank=True, null=True, verbose_name='Transit Duration (min)')),
            ],
            options={
                'verbose_name': 'Transit Travel Time',
                'verbose_name_plural': 'Transit Travel Times',
                'unique_together': {('station', 'hub')},
            },
        ),
    ]
