# Generated by Django 5.2 on 2025-05-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_bikeduration_transitduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationinfo',
            name='near_park',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stationinfo',
            name='safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stationinfo',
            name='shopping_street',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stationinfo',
            name='supermarket_dense',
            field=models.BooleanField(default=False),
        ),
    ]
