# Generated by Django 5.2 on 2025-05-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_stationinfo_near_park_stationinfo_safe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationinfo',
            name='station_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
