# Generated by Django 5.2 on 2025-05-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_stationinfo_station_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationinfo',
            name='station_photo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
