# Generated by Django 5.2 on 2025-05-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_stationinfo_station_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearbyfacility',
            name='photo_reference',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
