version: "3.8"

services:
  backend:
    build: ./backend
    container_name: django-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: react-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: osaka_db
      POSTGRES_USER: osaka_user
      POSTGRES_PASSWORD: osaka_pw
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  scraper:
    build:
      context: ./scraper/url
    volumes:
      - ./scraper/url:/scraper
    working_dir: /scraper
    command: sleep infinity
    depends_on:
      - db

  detail_scraper:
    build:
      context: ./scraper/detail
      dockerfile: Dockerfile
    volumes:
      - ./scraper/detail:/scraper
    working_dir: /scraper
    command: sleep infinity
    depends_on:
      - db
      
  station_scraper:
    environment:
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    build:
      context: ./scraper/station
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./scraper/station:/app

  


volumes:
  pgdata: